export enum ClFormControlTypes {
  INPUT_TEXT = 'INPUT_TEXT',
  INPUT_NUMBER = 'INPUT_NUMBER',
  INPUT_SWITCH = 'INPUT_SWITCH',
  CHIPS = 'CHIPS',
  INPUT_GROUP = 'INPUT_GROUP',
  CHECKBOX = 'CHECKBOX',
  RADIO_BUTTON = 'RADIO_BUTTON',
  MULTISELECT = 'MULTISELECT',
  SELECT = 'SELECT',
  TEXTAREA = 'TEXTAREA',
  DATEPICKER = 'DATEPICKER',
  FILE_UPLOADER = 'FILE_UPLOADER',
  SELECT_BUTTON = 'SELECT_BUTTON',
}
export type ClFormControlType = keyof typeof ClFormControlTypes;
