export type ClChartType = 'vertical-bar'
  | 'vertical-bar-stacked'
  | 'horizontal-bar-stacked'
  | 'horizontal-bar'
  | 'group-vertical-bar'
  | 'group-horizontal-bar'
  | 'pie'
  | 'pie-grid'
  | 'doughnut'
  | 'line'
  | 'area'
  | 'gauge'
  | 'bubble'
  | 'number-cards'
  | 'polar';
